-- Initial migration to verify Flyway is working.
CREATE TABLE schema_heartbeat (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO schema_heartbeat (note)
VALUES ('SQL Detective migrations are operational.');
