-- Case 01: The Blackwood Hotel — investigation tables

CREATE TABLE guests (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       TEXT        NOT NULL,
    room_number     INTEGER     NOT NULL CHECK (room_number BETWEEN 100 AND 999),
    check_in_date   DATE        NOT NULL,
    check_out_date  DATE        NOT NULL,
    vip_status      BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT guests_dates_chk CHECK (check_out_date >= check_in_date)
);

CREATE TABLE employees (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       TEXT        NOT NULL,
    job_title       TEXT        NOT NULL,
    shift_start     TIMESTAMPTZ NOT NULL,
    shift_end       TIMESTAMPTZ NOT NULL,
    access_level    TEXT        NOT NULL,
    CONSTRAINT employees_shift_chk CHECK (shift_end > shift_start),
    CONSTRAINT employees_access_level_chk CHECK (
        access_level IN ('BASIC', 'STAFF', 'MASTER')
    )
);

CREATE TABLE room_access_logs (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number     INTEGER     NOT NULL CHECK (room_number BETWEEN 100 AND 999),
    person_type     TEXT        NOT NULL,
    person_id       INTEGER     NOT NULL,
    entry_time      TIMESTAMPTZ NOT NULL,
    exit_time       TIMESTAMPTZ,
    access_method   TEXT        NOT NULL,
    CONSTRAINT room_access_person_type_chk CHECK (
        person_type IN ('guest', 'employee')
    ),
    CONSTRAINT room_access_method_chk CHECK (
        access_method IN ('KEYCARD', 'MASTER_KEY', 'STAFF_BADGE', 'FRONT_DESK')
    ),
    CONSTRAINT room_access_exit_chk CHECK (
        exit_time IS NULL OR exit_time >= entry_time
    )
);

CREATE TABLE payments (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id        INTEGER     NOT NULL REFERENCES guests (id),
    amount          NUMERIC(10, 2) NOT NULL CHECK (amount > 0),
    payment_type    TEXT        NOT NULL,
    payment_time    TIMESTAMPTZ NOT NULL,
    status          TEXT        NOT NULL,
    CONSTRAINT payments_type_chk CHECK (
        payment_type IN ('CASH', 'CARD', 'WIRE')
    ),
    CONSTRAINT payments_status_chk CHECK (
        status IN ('COMPLETED', 'PENDING', 'FAILED', 'REFUNDED')
    )
);

CREATE TABLE evidence_items (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           TEXT        NOT NULL,
    description     TEXT        NOT NULL,
    discovered_at   TIMESTAMPTZ NOT NULL,
    related_room    INTEGER     CHECK (related_room IS NULL OR related_room BETWEEN 100 AND 999)
);

CREATE TABLE challenges (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level_number    INTEGER     NOT NULL UNIQUE CHECK (level_number BETWEEN 1 AND 20),
    title           TEXT        NOT NULL,
    story_text      TEXT        NOT NULL,
    objective       TEXT        NOT NULL,
    starter_query   TEXT        NOT NULL,
    hint            TEXT        NOT NULL,
    success_clue    TEXT        NOT NULL,
    difficulty      TEXT        NOT NULL,
    order_sensitive BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT challenges_difficulty_chk CHECK (
        difficulty IN ('EASY', 'MEDIUM', 'HARD')
    )
);

CREATE INDEX idx_guests_room_number ON guests (room_number);
CREATE INDEX idx_guests_check_in_date ON guests (check_in_date);
CREATE INDEX idx_employees_access_level ON employees (access_level);
CREATE INDEX idx_room_access_logs_room_entry ON room_access_logs (room_number, entry_time);
CREATE INDEX idx_room_access_logs_person ON room_access_logs (person_type, person_id);
CREATE INDEX idx_payments_guest_id ON payments (guest_id);
CREATE INDEX idx_payments_payment_time ON payments (payment_time);
